### ISSUE TITLE
Jinja variable 'dict object' has no attribute 'iteritems'

### ISSUE THREAD

**Issue by MurzNN** [salt-formulas/salt-formula-rsyslog#17]
I trying to use this formula with simple pillar from example:
```yaml
rsyslog:
  client:
    enabled: true
    format:
      name: TraditionalFormatWithPRI
      template: '"%syslogpriority% %syslogfacility% %timestamp:::date-rfc3339% %HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"'
    output:
      file:
        -/var/log/syslog:
          filter: '*.*;auth,authpriv.none'
          user: syslog
          group: adm
          createmode: 0640
          umask: 0022
```
But got the error:
```
    Data failed to compile:
----------
    Rendering SLS 'base:rsyslog.client' failed: Jinja variable 'dict object' has no attribute 'iteritems'
```
Why this happens and how to fix it?
